### ISSUE TITLE
CEF seems to crash every time randomly

### ISSUE THREAD

**Issue by RealKalsep** [SpiralP/classicube-cef-plugin#2]
Hello, this didn't happen yesterday and before but I went to NA2 and played there for some time, during that I got 3 crashes with the same error.
I have version 0.14.6

https://pastebin.com/1fdNBWqZ

**Comment by RealKalsep** [comment]
Here is an image when the error happens (this is when I click in the "shrine" map and the chat message pops up) https://imgur.com/PjA0IX8

**Comment by SpiralP** [comment]
Fixed it in the [next update](https://github.com/SpiralP/classicube-cef-plugin/releases/tag/v0.15.0)!

You can replace the dll in `cef/classicube_cef_windows_x86_64.dll` or do singleplayer until it auto-updates.

**Comment by TheAwesome98-Real** [comment]
Completely off-topic but hi kalsep
